title: AxxonBlog
email: sebastien.grans@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Axxon is a french web developer and musician in a perpertual learning curve. 
    PHP/Symfony/DDD/TDD/OOP
    TechnoMusic/DJ/MAO(ModularSynth)
    Thoughts & Interests
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Axxon_
github_username:  Axxon

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
